SET "WORKSPACE=."

SET "BUILD_DEPENDENCIES=false"

SET "PYSETTINGS_GIT_BRANCH=master"
SET "PYFORMS_GIT_BRANCH=master"
SET "LOGGING_BOOTSTRAP_GIT_BRANCH=master"
SET "PYBRANCH_GIT_BRANCH=master"
SET "PGE_GIT_BRANCH=development"
SET "PYBPODAPI_GIT_BRANCH=development"
SET "PYBPODGUIPLUGIN_TIMELINE_GIT_BRANCH=master"
SET "PYBPODGUIPLUGIN_SESSION_HISTORY_GIT_BRANCH=master"

SET "WITH_MATPLOTLIB=false"
SET "WITH_PYQT_WEB=false"
