# !/usr/bin/python3
# -*- coding: utf-8 -*-

# from enum import IntEnum, unique

class BoardOperations():
	# INSTALL FRAMEWORK OPERATIONS
	INSTALLFRAMEWORK_LOAD_FILES = 0
	INSTALLFRAMEWORK_IMPORT_PYCONTROL = 4

	# UPLOAD TASK OPERATIONS
	UPLOADTASK_UPLOAD_TASK_FILE = 5
	UPLOADTASK_IMPORT_FRAMEWORK = 7
	UPLOADTASK_IMPORT_TASK = 8

	# SYNC VARIABLES OPERATIONS
	SYNCVARIABLES_IMPORT_TASK = 9
	SYNCVARIABLES_SET_VARIABLE = 10
	SYNCVARIABLES_GET_VARIABLE = 11
	SYNCVARIABLES_PRINT_VARIABLES = 12

	# RUN TASK OPERATIONS
	RUNTASK_SYNC_VARIABLES = 13
	RUNTASK_CHECK_TASK_INSTALLED = 14
	RUNTASK_PRINT_VARIABLES = 15
	RUNTASK_IMPORT_FRAMEWORK = 16
	RUNTASK_PRINT_EVENTS = 17
	RUNTASK_PRINT_STATES = 18
	RUNTASK_SET_VERBOSE = 19
	RUNTASK_SET_DATA_OUTPUT = 20
	RUNTASK_RUN_FRAMEWORK = 21
	RUNTASK_PRINT_NEW_VARIABLES = 22
	RUNTASK_STOP_FRAMEWORK = 23
